### ISSUE TITLE
[Feature Request] Custom API endpoint?

### ISSUE THREAD

**Issue by iandol** [afadingthought/kiki-ai-workflow#2]
There are some great local LLM tools:

https://lmstudio.ai
https://gpt4all.io/index.html
https://ollama.com

They run OpenAI compatible server locally on your Mac, and with an 8-16GB Apple Silicon mac you can run fairly powerful LLMs totally locally, no API keys or costs. For this you need to add a custom API address, e.g. `http://127.0.0.1:4891`. It would be nice if you could add this as an option...

**Comment by iandol** [comment]
@afadingthought — I can make a pull request for this if you'd like, as long as I understand the main code is the bash script embedded in the workflow:

https://github.com/afadingthought/kiki-ai-workflow/blob/main/Kiki/info.plist#L4661

So if i edit this bash script we should be able to override `API_URL`?

**Comment by afadingthought** [comment]
> @afadingthought — I can make a pull request for this if you'd like, as long as I understand the main code is the bash script embedded in the workflow:
> 
> https://github.com/afadingthought/kiki-ai-workflow/blob/main/Kiki/info.plist#L4661
> 
> So if i edit this bash script we should be able to override `API_URL`?

I've just release v1.1.1 which has the main bash script as [a separate file](https://github.com/afadingthought/kiki-ai-workflow/blob/main/Kiki/scripts/request.sh). And yes, it's the API_URL variable you probably want to override.
