### ISSUE TITLE
[Question] Ollama setup

### ISSUE THREAD

**Issue by hamorillo** [afadingthought/kiki-ai-workflow#4]
Have you tried using Ollama with the workflow? I'm trying to set it up, but for some reason, it doesn't work. 

<img width="551" alt="image" src="https://github.com/afadingthought/kiki-ai-workflow/assets/6974554/efc7f095-d26a-451a-979b-20d2cd0d1eef">

Sometimes the dialog doesn't open at all. Others I see the following:

<img width="422" alt="image" src="https://github.com/afadingthought/kiki-ai-workflow/assets/6974554/d5baaec0-3dab-4c41-bcef-16ca22e93d87">

Any idea?

**Comment by afadingthought** [comment]
Hi there! Kiki currently takes OpenAI API compatible requests, I just checked and [Ollama supports this](https://github.com/ollama/ollama/blob/main/docs/openai.md#ybf), but the endpoint URL is different. Could you try with: http://127.0.0.1:11434/v1/chat/completions

**Comment by afadingthought** [comment]
I've now personally tested with Ollama and can confirm that the Endpoint URL has to be set to http://127.0.0.1:11434/v1/chat/completions (with the default config). I've also just released [a new update](https://github.com/afadingthought/kiki-ai-workflow/releases/latest) that improves the custom Endpoint URL functionality.

**Comment by hamorillo** [comment]
Hey @afadingthought ! I've tried, and it works great! Thank you so much! 

Really nice job! ❤️
