### ISSUE TITLE
Support custom API_ENDPOINT_URL + API KEY

### ISSUE THREAD

**Issue by Dima-Kal** [afadingthought/kiki-ai-workflow#5]
Hey this workflow looks very promising, thanks for the work!
I would suggest adding support for both custom API url and API key interoperability
for example you have service like "groq" that provides free API key and supports OpenAI api, so by setting in the workflow OpenAI api key with the groq url ("https://api.groq.com/openai/v1/chat/completions") or just add new custom api key field for the custom url API endpoint

for now to make it work on my setup i just edited the "requests.sh" file in the OpenAI request (if api key provided) to use the groq url enpoint hardcoded

**Comment by afadingthought** [comment]
Added and tested with Groq in the most recent release. Aside from adding the Groq URL and Token, do make sure to add the  "custom_" prefix in the model fields to indicate you need requests directed to your API Endpoint URL.
